### ISSUE TITLE
AR12MSPXBWKN stoped working after updating from 6.0.1

### ISSUE THREAD

**Issue by stefan-dumitrescu** [atxbyea/samsungrac#103]
The integration worked flawlessly til i tried updating to version 6.2.
After the update i noticed that the card shows no mode/data/etc.
The only thing that worked was removing the integration and installing version 6.0.1.
![Screenshot 2024-07-18 at 14 31 38](https://github.com/user-attachments/assets/0d9b0a91-ce4f-4c5c-b1da-0cc155077e47)
Nothing changed in the configuration.yaml
Also tried adding the "cert:" line but didn't do anything.

**Comment by Il3a7x** [comment]
I confirm same problem... downgraded and everything worked again. It is not the first time that some user who proposes the update does more damage than improvement

The question, however, is simple... considering that our Samsung AR are now old, it is better to avoid updating Climate IP... anyway it cannot bring any benefit, but on the contrary cause damage

**Comment by stefan-dumitrescu** [comment]
To be honest I only updated because i'm missing a few things:
- the ability to reset the filter alarm (and optionally receive an alert when. the timer/alarm has activated)
- to see the power consumption details
- to activate the purification/clean/ionisation mode
I tried thru the yaml but couldn't make them work and that's why i keep trying the updates.

**Comment by Il3a7x** [comment]
for the purify, autoclean etc. functions they are already there... you just have to insert some switches in configuration.yaml and then call them on the dashboard.

**Comment by stefan-dumitrescu** [comment]
> for the purify, autoclean etc. functions they are already there... you just have to insert some switches in configuration.yaml and then call them on the dashboard.

By any chance, do you have an example that you can share?
For me it wouldn't work when i first integrated the ac unit so i hoped that there is something in the repo.
<img width="572" alt="Screenshot 2024-07-19 at 14 07 59" src="https://github.com/user-attachments/assets/d6c3e8c2-a030-4666-bc58-a72be43b3060">
<img width="576" alt="Screenshot 2024-07-19 at 14 08 25" src="https://github.com/user-attachments/assets/ce27bb3b-2a8e-4c20-b685-27bb241575fb">
as you can see everything else works now...

**Comment by Il3a7x** [comment]
no, you have to create it as a separate switch (photo attached).

![Screenshot_20240719_151037](https://github.com/user-attachments/assets/93684d30-203e-4e13-a259-708c963829fd)

First of all, put the code in configuration.yaml:
p.s.: 
- in unique_id enter the token of the Samsung air conditioner. 
- In value_template and entity_id the name of your Samsung air conditioner... use _ (underscore) instead of empty spaces (I have already put the correct name in the code as your screenshot)

`switch:
  - platform: template
    switches:
      auto_clean:
        unique_id: YOURTOKEN
        value_template: "{{ is_state_attr('climate.ac_living_room', 'auto_clean', 'on') }}"
        turn_on:
          service: climate.climate_ip_set_property
          data:
            entity_id: climate.ac_living_room
            auto_clean: 'on'
        turn_off:
          service: climate.climate_ip_set_property
          data:
            entity_id: climate.ac_living_room
            auto_clean: 'off'`

then go to the overview of your dashboard and click on the pen icon to start editing. Locate a room where you want to create the "auto clean" switch and click edit... at the bottom add an entity and search for "auto clean ac living room". Now you have a toggle to enable auto clean.
If so, add another switch in configuration.yaml if you have multiple Samsung air conditioners.
 You can do the same thing for a "purify" switch etc.. (example for purfy function, replacing all "auto_clean" terms in the code with "purify")
