### ISSUE TITLE
Error in logs although everything works...

### ISSUE THREAD

**Issue by sebos13** [atxbyea/samsungrac#91]
Hello there,

I'm getting this error in the logs, although everything works fine... It's not a big deal, but I thought I'd let you know.
Running latest samsungrac 6.0.1 with the latest HAOS (2024.2.1) and a Samsung AR18HSFS air conditioner (old gen, port 2878).

Logger: homeassistant.components.climate
Source: components/climate/__init__.py:354
Integration: Climate ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 8:59:44 AM (3 occurrences)
Last logged: 8:59:44 AM

Entity None (<class 'custom_components.climate_ip.climate.ClimateIP'>) does not set ClimateEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/atxbyea/samsungrac/issues
Entity None (<class 'custom_components.climate_ip.climate.ClimateIP'>) does not set ClimateEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/atxbyea/samsungrac/issues
Entity None (<class 'custom_components.climate_ip.climate.ClimateIP'>) implements HVACMode(s): cool, heat, dry, fan_only, heat_cool, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/atxbyea/samsungrac/issues

**Comment by Alexciao** [comment]
Same

**Comment by atxbyea** [comment]
Do you still have this message @Alexciao @sebos13

**Comment by Alexciao** [comment]
I will update and let you know

**Comment by sebos13** [comment]
Updated now, same message in the logs, everything still works fine !

**Comment by samuelecarpene** [comment]
I think the problem is the same described [here](https://community.home-assistant.io/t/climate-implicitly-supports-the-turn-on-turn-off-methods-without-setting-the-proper-climateentityfeature/688028).

It is described [here](https://developers.home-assistant.io/blog/2024/01/24/climate-climateentityfeatures-expanded/) in the blog..

I think the problem can be fixed following this [fix ](https://github.com/kamaradclimber/heishamon-homeassistant/commit/0ac5769d64848b8c46feb69c6260dc7a53bd3242) made on another climate custom components.

I'll try to work on this.
